services:
  - type: web
    name: thalium-bank
    env: python
    region: oregon
    plan: free
    buildCommand: "./render-build.sh"
    # Run migrations and seed admin on start before app launch
    startCommand: "flask db upgrade && flask seed_admin && gunicorn -w 4 -b 0.0.0.0:$PORT app:app"
    envVars:
      - key: FLASK_APP
        value: app.py
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: thalium-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: thalium-redis
          property: connectionString

databases:
  - name: thalium-db
    databaseName: thaliumbank
    plan: free
    region: oregon

services:
  - type: redis
    name: thalium-redis
    region: oregon
    plan: free
